#!/bin/bash

#SBATCH --job-name=d2q9-bgk
#SBATCH --account=COMS037985
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:10:00
#SBATCH --output=d2q9-bgk.out
#SBATCH --exclusive

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

export OMP_NUM_THREADS=12
export OMP_PLACES=cores
export OMP_PROC_BIND=close

GRID=128x128
#GRID=128x256
#GRID=256x256
#GRID=1024x1024

#! Run the executable
# perf stat -e cycles,instructions,cache-references,cache-misses --
./d2q9-bgk input_$GRID.params obstacles_$GRID.dat
make check REF_AV_VELS_FILE=check/$GRID.av_vels.dat REF_FINAL_STATE_FILE=check/$GRID.final_state.dat
